---
- set_fact:
    os_type: "{{ ansible_distribution }}{{ ansible_distribution_major_version }}"


- name: install dwave-ocean-sdk
  pip:
    name: dwave-ocean-sdk

#- include: prepare.yml env={{item}}
  #with_items: "{{ install_envs }}"

#- include: install.yml env={{item}}
#  with_items: "{{ install_envs }}"
